# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojccJw2YUj0r-8eEajwqe5LTNGStuyHW
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d utkarshx27/heart-disease-diagnosis-dataset

import zipfile
zip_ref = zipfile.ZipFile('/content/heart-disease-diagnosis-dataset.zip')
zip_ref.extractall('/content')
zip_ref.close()

import numpy as np
import pandas as pd